/************************************************************************/
/* MCI Display Message Support Defs: MCIMsg.h           V2.00  07/15/94 */
/* Copyright (c) 1987-1995 Andrew J. Michalik                           */
/*                                                                      */
/************************************************************************/

/************************************************************************/
/*                  MCI Operation Request Messages                      */
/************************************************************************/
#define SI_MCIUNKMSG    0 + MCIGLOBAS   /* Unknown MCI message          */
#define MCILSTMSG       0 + MCIGLOBAS   /* MCI DLL last message         */


