REM Set source files
fd *.*                  /t12:00/d01-15-99
fd CIFDEV\*.*           /t12:00/d01-15-99
fd HLPDEV\*.*           /t12:00/d01-15-99
fd RES\*.*              /t12:00/d01-15-99
fd CIFDEV\*.*           /t12:00/d01-15-99
fd CIFDEV\AMPDEV\*.*    /t12:00/d01-15-99
fd CIFDEV\EFFDEV\*.*    /t12:00/d01-15-99
fd CIFDEV\FIODEV\*.*    /t12:00/d01-15-99
fd CIFDEV\MCIDEV\*.*    /t12:00/d01-15-99
fd CIFDEV\OS_DEV\*.*    /t12:00/d01-15-99
fd CIFDEV\PCMDEV\*.*    /t12:00/d01-15-99
fd CIFDEV\REGDEV\*.*    /t12:00/d01-15-99
fd CIFDEV\RES\*.*       /t12:00/d01-15-99
fd CIFDEV\TMIDEV\*.*    /t12:00/d01-15-99
REM Set executable files
fd *.EXE                /t12:00/d01-15-99
fd VFECIF.DLL           /t12:00/d01-15-99
fd EXEDEV\DLG???.DLL    /t12:00/d01-15-99
fd EXEDEV\G21???.DLL    /t12:00/d01-15-99
fd EXEDEV\HAR???.DLL    /t12:00/d01-15-99
fd EXEDEV\NWV???.DLL    /t12:00/d01-15-99
fd EXEDEV\PTC???.DLL    /t12:00/d01-15-99
fd EXEDEV\RTX???.DLL    /t12:00/d01-15-99
