//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by VFECIF.RC
//
#define IDR_VFEARRPTR                   5
#define IDR_VFESELMRK                   6
#define IDD_PROMPT                      101
#define IDR_VISLGO                      102
#define IDC_BIT0                        256
#define IDC_BIT1                        257
#define IDC_BIT2                        258
#define IDC_BIT3                        259
#define IDC_BIT4                        260
#define IDC_ENABLEALL                   512

#define IDS_CIFLIBNAM                   200
#define IDS_VFEAUDTYP                   210
#define IDS_UNKAUDDEV					222
#define IDS_SELBSTFMT					224

#define IDS_CIFDLLSUP					250
#define IDS_AMPDLLSUP					252
#define IDS_EFFDLLSUP					254
#define IDS_FIODLLSUP					256
#define IDS_MCIDLLSUP					258
#define IDS_PCMDLLSUP					260
#define IDS_TMIDLLSUP					262

#define IDS_ACCKEYNON					500
#define IDS_MODVERMIS					502
#define IDS_DOSMEMERR					504
#define IDS_INSMEMERR					506
#define IDS_OPNFILERR					508
#define IDS_TMPDIRERR					510
#define IDS_TMPCREERR					512
#define IDS_TMPCREREP					514
#define IDS_TMPRENERR					516
#define IDS_TMPDELERR					518
#define IDS_MASBAKERR					520
#define IDS_MASRESERR					522
#define IDS_MASLODERR					524
#define IDS_WRKLODERR					526
#define IDS_SNPLODERR					528
#define IDS_TXTLODERR					530
#define IDS_UNDACCERR					532
#define IDS_CUTFILERR					534
#define IDS_SHFFILERR					536
#define IDS_TXTWRTERR					538
#define IDS_SNPWRTERR					540
#define IDS_WRKWRTERR					542
#define IDS_SEGSELERR					544
#define IDS_SEGUPDERR					546
#define IDS_SEGCREERR					548
#define IDS_SEGDELERR					550
#define IDS_EBSEOSERR					552
#define IDS_DCEALOERR					554
#define IDS_ECHALOERR					556
#define IDS_FADALOERR					558
#define IDS_POWALOERR					560
#define IDS_EQUFFTERR					562
#define IDS_EQUALOERR					564

#define IDS_SEGCREWRN					600
#define IDS_SEGDELWRN					602

#define IDS_USRCANREQ           		700

#define	IDS_AAFALGNON					800
#define	IDS_AAFALGFST					802
#define	IDS_AAFALGNRM					804
#define	IDS_AAFALGFFT					806
#define	IDS_AAFALG6II					808
#define	IDS_AAFALG6IF					810
#define	IDS_AAFALGERR					812

#define	IDS_RESALGNON					820
#define	IDS_RESALGFST					822
#define	IDS_RESALGNRM					824
#define	IDS_RESALGFFT					826
#define	IDS_RESALGERR					828

#define	IDS_DTMALGNON					840
#define	IDS_DTMALGFFT					842
#define	IDS_DTMALGERR					844

#define	IDS_POLACTMAS					900
#define	IDS_POLACTSNP					902
#define	IDS_POLACTGPH					904
#define	IDS_POLACTCUE					906
#define	IDS_POLACTLOG					908
#define	IDS_POLACTSHF					910
#define	IDS_POLACTOVR					912
#define	IDS_POLACTCOP					914
#define	IDS_POLACTCVT					916
#define	IDS_POLACTERA					918
#define	IDS_POLACTUND					920
#define	IDS_POLACTRED					922
#define	IDS_POLACTPLA					924
#define	IDS_POLACTREC					926
#define	IDS_POLACTUPD					928
#define	IDS_POLACTSAV					930
#define	IDS_POLACTSCN					932
#define	IDS_POLACTPOW					934
#define	IDS_POLACTTON					936

#define	IDS_DEMLIMERR				 	 -2
#define	IDS_UNKMSGERR				     -1

//Should passed in from VB parent
#define IDS_COLSEC                      1400
#define IDS_COLSEC_CTLBKG               1402
#define IDS_COLSEC_CTLTXT               1404

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        105
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
