/************************************************************************/
/* File I/O Display Msg Support Defs: FIOMsg.h          V2.00  07/15/94 */
/* Copyright (c) 1987-1995 Andrew J. Michalik                           */
/*                                                                      */
/************************************************************************/
int WINAPI  FIODspPrc (HWND, LPCSTR, LPCSTR, UINT);
long        GetPrfLng (LPCSTR, LPCSTR, WORD, long);

