#
# Standard compiler command line switches
#	d       Redefined macros
#	c       No link
#	AM      Medium memory model
#	Gsw     Stack probes & Windows
#	G2      80286 Instruction Set
#	Gh      C5.1 compatible object
#	Ox      Max optimization (Note: C6.00a float op error for "ei")
#	Od      No optimization
#	W2      Intermediate warning level
#	Zp      Structure packing
#	Zd      Symbolic Debug
#	Zi      CodeView Debug
#	NT      Named text (code area) follows
#	Alnw	Check for DS==SS
#	V       Imbed version string
#
# Standard linker command line switches
#   NOD     No default library
#   A:x     Segment alignment (default = 512 bytes)
#   SE:x    Set max number of segments

# -----------------------------------------------------------------------
# Compile and Link options (distribution & debug)
# -----------------------------------------------------------------------
!IFDEF deb
# ---- DEBUG ----
ap=masm/MX/V/ZI
cp=cl -c -FoObject\ $(W_Defs) -D$(C_Defs) -V$(V_Note) -W3 -AM  -G2 -Gsw -Zp -FPa -Od -Zi
cd=cl -c -FoObject\ $(W_Defs) -D$(C_Defs) -V$(V_Note) -W3 -AMw -G2 -Gsw -Zp -FPa -Od -Zi 
lp=$(linker)/NOD/NOE/A:16/CO$(L_Defs)
!ELSE
# ---- Default: DISTRIBUTION ----
ap=masm/MX/V
cp=cl -c -FoObject\ $(W_Defs) -D$(C_Defs) -V$(V_Note) -W3 -AM  -G2 -Gsw -Zp -FPa -Ocglt  
cd=cl -c -FoObject\ $(W_Defs) -D$(C_Defs) -V$(V_Note) -W3 -AMw -G2 -Gsw -Zp -FPa -Ocglt 
lp=$(linker)/NOD/NOE/A:16$(L_Defs)
!ENDIF

# -----------------------------------------------------------------------
# Version Control and Copyright Defs
# -----------------------------------------------------------------------
V_Note = "Copyright AJM, 800-234-VISI"

# -----------------------------------------------------------------------
# Hardware specific build paths
# -----------------------------------------------------------------------
# ---- DIALOGIC ----
C_Defs = DLG

# -----------------------------------------------------------------------
# Windows version Library build paths & Copy Destination paths
# -----------------------------------------------------------------------
!IFDEF w30
# ---- Windows 3.0 ----
WinLib = libw+win87em+mlibcew
DLLLib = libw+win87em+mdllcew
W_Defs = -I\w30dev\include -D$(C_Defs)
W_Stub =
DstPth = \windows^\
LibEnt = \w30dev\lib\libentry.obj
DLLExt = dll
linker = link
rc = \w30dev\rc $(W_Defs)
rd = \w30dev\rc $(W_Defs)
!ELSE
# ---- DEFAULT C8 & Win 3.1 ----
WinLib = libw+mlibcew
DLLLib = libw+mdllcew
W_Defs = -I\w31dev\include -D$(C_Defs)
W_Stub =
DstPth = \w31ret^\
LibEnt =
DLLExt = dll
linker = link
rc = rc $(W_Defs)
rd = rc $(W_Defs)
!ENDIF

# -----------------------------------------------------------------------
# Standard inference rules
# -----------------------------------------------------------------------
.c{object\}.obj:
    $(cp) $(@B).c
.cpp{object\}.obj:
    $(cp) $(@B).cpp

# -----------------------------------------------------------------------
# The Target File List
# -----------------------------------------------------------------------
dlgtst.exe: object\dlgtst.obj ..\dlgxlt.lib
    $(lp)   object\dlgtst.obj, dlgtst, NUL, ..\dlgxlt.lib + mlibce;

..\dlgxlt.lib: object\dlgxl1.obj object\dlgxl2.obj dlgxl1.tab dlgxl2.tab 
            del ..\dlgxlt.lib
            lib ..\dlgxlt.lib -+object\dlgxl1.obj -+object\dlgxl2.obj;

dlgxl1.tab: xl1tab.exe
            xl1tab > dlgxl1.tab

xl1tab.exe: object\xl1tab.obj object\xl1sim.obj
    $(lp)   object\xl1tab.obj + object\xl1sim.obj,, NUL, mlibce;

dlgxl2.tab: xl2tab.exe 
            xl2tab > dlgxl2.tab

xl2tab.exe: object\xl2tab.obj object\xl2sim.obj
    $(lp)   object\xl2tab.obj + object\xl2sim.obj,, NUL, mlibce;


# -----------------------------------------------------------------------
# The C and assembly File List
# -----------------------------------------------------------------------
object\dlgtst.obj: dlgtst.c ..\genpcm.h
object\xl1tab.obj: xl1tab.c xltsim.h    ..\genpcm.h
object\xl1sim.obj: xl1sim.c xltsim.h    ..\genpcm.h
object\dlgxl1.obj: dlgxl1.c dlgxl1.tab  ..\pcmsup.h ..\genpcm.h
    $(cd) dlgxl1.c
object\xl2tab.obj: xl2tab.c xltsim.h    ..\genpcm.h
object\xl2sim.obj: xl2sim.c xltsim.h    ..\genpcm.h
object\dlgxl2.obj: dlgxl2.c dlgxl2.tab  ..\pcmsup.h ..\genpcm.h
    $(cd) dlgxl2.c

